name: Lint Commit Messages
on: [pull_request]
jobs:
  commitlint:
    runs-on: jimdo-runner-1core
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v5
        with:
          configFile: './.commitlint.config.js'
